name: Build Birdseye 0.17.2 Images

on:
  workflow_dispatch:

concurrency:
  group: build-birdseye-0172
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build_tensorrt:
    runs-on: ubuntu-22.04
    name: Build TensorRT amd64 image
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up QEMU and Buildx
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push TensorRT image
        env:
          COMPUTE_LEVEL: "50 60 70 80 90"
        uses: docker/bake-action@v6
        with:
          source: .
          push: true
          targets: tensorrt
          files: docker/tensorrt/trt.hcl
          set: |
            tensorrt.tags=ghcr.io/thorstenum/frigate:0.17.2-tensorrt
